---
- name: Create folder file agent nxlog
  ansible.windows.win_file:
    path: "{{ Folder_Agent }}"
    state: directory

- name: Create folder install Nxlog
  ansible.windows.win_file:
    path: "{{ INSTALLDIR }}"
    state: directory

- - name: Coppy file agent nxlog
  ansible.windows.win_copy:
    src: "file/{{ Agent_Nxlog }}"
    dest: "{{ Folder_Agent }}"

- name: Installed Nxlog via win_command
  win_command: msiexec /i {{ Folder_Agent }}\{{ Agent_Nxlog }} /qb INSTALLDIR="{{ INSTALLDIR }}"
  wait: yes

  
- name: Remove file Config nxlog.conf
  ansible.windows.win_file:
    path: "{{ file_config }}"
    state: absent

- name: Coppy file config nxlog
  ansible.windows.win_copy:
    src: "templates/nxlog.conf.j2"
    dest: "{{ file_config }}"
  notify: Restart-nxlog