---
- name: Create folder file agent nxlog
  win_file:
    path: "{{ Folder_Agent }}"
    state: directory

- name: Create folder install Nxlog
  win_file:
    path: "{{ INSTALLDIR }}"
    state: directory

- name: Coppy file agent nxlog
  win_copy:
    src: "files/{{ Agent_Nxlog }}"
    dest: "{{ Folder_Agent }}"

- name: Installed Nxlog
  win_shell: msiexec /i {{ Folder_Agent }}\{{ Agent_Nxlog }} /qb INSTALLDIR={{ INSTALLDIR }}


- name: Remove file Config nxlog.conf
  win_file:
    path: "{{ file_config }}"
    state: absent

- name: Coppy file config nxlog
  win_copy:
    src: "templates/nxlog.conf.j2"
    dest: "{{ INSTALLDIR }}/{{ file_config }}/nxlog.conf"
  notify: Restart-nxlog

- name: Check Service status
  win_shell: Get-Service nxlog
  register: status

- debug: msg={{ status.stdout_lines }}