---
# Tạo thư mục chưa source code và file config
- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ local_DocumentRoot }}"
  - "{{ local_conf }}"


# Pull image docker
- name: Pull image PHP
  docker_image:
    name: "{{ Image_PHP }}"
    source: pull

# Pull image docker
- name: Pull image httpd
  docker_image:
    name: "{{ Image_Apache }}"
    source: pull

# Create Network local
- name: Create a network with options
  docker_network:
    name: "{{ network }}"
    driver_options:
      com.docker.network.bridge.name: net2
    ipam_options:
      subnet: "{{ subnet }}"
      gateway: "{{ gateway }}"
      iprange: "{{ iprange }}"
# Coppy file
- name: Coppy file index.php
  template:
    src: "templates/index.php.j2"
    dest: "{{ local_DocumentRoot }}/index.php"

- name: Coppy file httpd.conf
  template:
    src: "templates//httpd.conf.j2"
    dest: "{{ local_conf }}/httpd.conf"

# Create container

- name: Create a docker container php7.4
  docker_container:
    name: "{{ name_php_container }}"
    image: "{{ Image_PHP }}"
    volumes:
      - "{{ local_DocumentRoot }}:{{ container_DocumentRoot }}"
    state: started

- name: Create a docker container apache
  docker_container:
    name: "{{ name_apache_container }}"
    image: "{{ Image_Apache }}"
    volumes:
      - "{{ local_DocumentRoot }}:{{ container_DocumentRoot }}"
      - "{{ local_conf }}/httpd.conf:{{ container_conf }}/httpd.conf"
    ports:
      - '{{ http_port }}:{{ http_port }}'
      - '{{ https_port }}:{{ https_port }}'
    state: started


- name: Add a container to a network, leaving existing containers connected
  docker_network:
    name: "{{ network }}"
    connected:
      - "{{ name_php_container }}"
      - "{{ name_apache_container }}"
    appends: yes