---
- name: Update repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  when: ansible_distribution == 'Ubuntu'

- name: Upgrade all apt packages
  apt: upgrade=dist
  when: ansible_distribution == 'Ubuntu'



- name: Install packages necessary for APT to use a repository over HTTPS
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: yes
    install_recommends: no
    state: present

- name: Add official Docker GPG key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  when: ansible_distribution == 'Ubuntu'

# cài đặt APT repository
- name: Add official Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: 'docker-official'
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

# Cài đặt docker
- name: Install docker-ce and docker-compose
  apt:
    pkg:
      - docker-ce
      - docker-compose
    update_cache: yes
    install_recommends: yes
    state: present

# add user vào group docker
- name: Add users to the Docker group
  user:
    name: "{{ group_user }}"
    groups: docker
    append: yes

# kiểm tra trạng thái docker sau khi cài đặt
- name: checking service status docker
  command: systemctl status "{{ item }}"
  with_items:
  - docker
  register: result
  ignore_errors: yes

- name: showing report
  debug:
   var: result

# kiểm tra phiên bản cài đặt
- name: checking version docker
  command: docker -v
  register: version
  ignore_errors: yes

- name: showing report
  debug:
   var: version