---
# Create Folder Setup Agent Zabbix
- name: Create folder install Agent Zabbix
  win_file:
    path: "{{ INSTALLFOLDER }}"
    state: directory

- name: Create folder save Agent Zabbix
  win_file:
    path: "{{ AGENTFOLDER }}"
    state: directory

# Coppy file Agent
- name: Coppy file agent Zabbix
  win_copy:
    src: "files/zabbix_agent-5.4.8-windows-amd64-openssl.msi"
    dest: "{{ AGENTFOLDER }}zabbix_agent-5.4.8-windows-amd64-openssl.msi"


- name: Install an MSI file
  win_msi:
    path: {{ AGENTFOLDER }}zabbix_agent-5.4.8-windows-amd64-openssl.msi /qn LOGTYPE=file LOGFILE={{ INSTALLFOLDER }}\zabbix.log SERVER={{ SERVER }} LISTENPORT={{ LISTENPORT }} SERVERACTIVE={{ SERVERACTIVE }} HOSTNAME={{ HOSTNAME }} ENABLEPATH={{ ENABLEPATH }} 


# Install Agent Zabbix on Window Server 2016
- name: Installed Agent Zabbix 
  win_shell: msiexec /l*v /i {{ AGENTFOLDER }}zabbix_agent-5.4.8-windows-amd64-openssl.msi /qn LOGTYPE=file LOGFILE={{ INSTALLFOLDER }}\zabbix.log SERVER={{ SERVER }} LISTENPORT={{ LISTENPORT }} SERVERACTIVE={{ SERVERACTIVE }} HOSTNAME={{ HOSTNAME }} ENABLEPATH={{ ENABLEPATH }} 


- name: Check Service status
  win_shell: Get-Service Zabbix Agent
  register: status

- debug: msg={{ status.stdout_lines }}